"""Build a standalone HTML evidence report from recorded test results."""
import html,json,pathlib
from datetime import datetime,timezone
ROOT=pathlib.Path(__file__).resolve().parent

def build():
    r=json.loads((ROOT/'results/results.json').read_text(encoding='utf-8'))
    cases=r['cases'];latency=next(c['summary_latency_us'] for c in cases if 'summary_latency_us' in c)
    pipeline=next(c['local_read_latency_ms'] for c in cases if 'local_read_latency_ms' in c)
    passed=r['tests_run']-r['failures']-r['errors']-r['skips']
    success=not(r['failures'] or r['errors'] or r['skips'])
    evidence=[]
    for case in cases:
        label=case['scenario'].split('_',2)[2].replace('_',' ').capitalize()
        delta=case['final_bank']['accounts']['a-main']-case['initial_bank']['accounts']['a-main']
        transfers=case['final_bank']['transfers']-case['initial_bank']['transfers']
        amount=f'{abs(delta)//100:,}.{abs(delta)%100:02}'
        change=('−' if delta<0 else '+' if delta>0 else '')+'$'+amount
        detail=html.escape(json.dumps(case,indent=2))
        evidence.append(f'<details><summary><span>{html.escape(label)}</span><span class="effect">{transfers} transfer(s) · {change} source change</span></summary><pre>{detail}</pre></details>')
    style='''
    :root{font-family:Inter,Segoe UI,Arial,sans-serif;color:#172637;background:#eef2f5}*{box-sizing:border-box}body{margin:0}main{max-width:1100px;margin:auto;padding:36px 24px 64px}header{background:#102b40;color:white;padding:34px;border-radius:18px}h1{font-size:36px;letter-spacing:-1px;margin:10px 0 14px}header p{max-width:780px;line-height:1.6;color:#d2e4ef}.eyebrow{text-transform:uppercase;letter-spacing:2px;font-size:12px;color:#9ed9cc}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin:22px 0}.card,section{background:white;border-radius:14px;padding:22px}.value{font-size:34px;font-weight:750;color:#116d56}.label{margin-top:8px;color:#4a6173;font-size:14px}section{margin-top:20px}h2{margin:0 0 14px;font-size:23px}p,li{line-height:1.6}.notice{background:#fff8e9;border-left:4px solid #d69521;padding:16px;margin:18px 0}.small{font-size:13px;color:#506274}table{width:100%;border-collapse:collapse;font-size:14px}th{text-align:left;color:#4a6173;background:#f2f6f9}td,th{padding:12px;border-bottom:1px solid #e4ebef;vertical-align:top}code{font-family:Consolas,monospace;background:#edf2f5;padding:2px 5px;border-radius:4px}.tablewrap{overflow-x:auto}details{border:1px solid #dfe7ed;border-radius:9px;margin:9px 0}summary{cursor:pointer;padding:15px;display:flex;justify-content:space-between;gap:12px;font-size:14px}summary:hover{background:#f3f8fa}.effect{font-size:12px;color:#577082;white-space:nowrap}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f7f9;margin:0;padding:18px;font-size:12px;line-height:1.5}footer{padding-top:22px;color:#607586;font-size:12px}@media(max-width:700px){.cards{grid-template-columns:1fr}h1{font-size:28px}summary{display:block}.effect{display:block;margin-top:8px}header{padding:24px}main{padding:18px 12px}}
    '''
    page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pramagent · Mock bank baseline</title><style>{style}</style></head><body><main>
    <header><div class="eyebrow">Local engineering evidence · {html.escape(str(r.get('baseline_version','')))}</div><h1>What happened to the money?</h1><p>A reproducible mock banking workflow that checks proposed actions against task scope, approvals and limits—and verifies the resulting synthetic balances.</p><p><strong>Pramagent v0.8.9 + a new reference controller.</strong> Separate local bank process. No network calls, model calls, or real money.</p></header>
    <div class="cards"><div class="card"><div class="value">{passed} / {r['tests_run']}</div><div class="label">Scenario tests passed · {r['skips']} skipped</div></div><div class="card"><div class="value">{r.get('operations_registered','?')} ops</div><div class="label">Bank operations under task-scoped control · {r.get('forbidden_operations','?')} permanently forbidden</div></div><div class="card"><div class="value">{r.get('chain_rules','?')} chains</div><div class="label">Multi-step escalation rules enforced across the operation surface</div></div></div>
    <div class="notice"><strong>Evidence boundary:</strong> {'All recorded scenarios passed.' if success else 'This run has failures or skips; inspect the raw output.'} This demonstrates the documented local configuration. It does not establish that an arbitrary real bank integration will behave identically. No model deception or prompt-injection success rate was measured.</div>
    <section><h2>The demonstration contract</h2><div class="tablewrap"><table><tr><th>Property</th><th>Configured behavior</th></tr><tr><td>Starting account</td><td>a-main · USD 10,000, tenant-a</td></tr><tr><td>Permitted beneficiary</td><td>a-vendor</td></tr><tr><td>Automatic transfer threshold</td><td>Up to USD 500 unless Pramagent separately escalates</td></tr><tr><td>Human approval</td><td>Required above USD 500; bound to the exact operation and policy revision</td></tr><tr><td>Hard transfer / task limits</td><td>USD 2,000 per transfer / USD 5,000 cumulative; uncertain outcomes stay charged</td></tr><tr><td>Execution</td><td>One controller, thread serialization, SQLite journals, local pipe to a separate bank process</td></tr></table></div><p class="small">All accounts, amounts and thresholds are synthetic test choices, not banking requirements.</p></section>
    <section><h2>Expected behavior, observed effects</h2><div class="tablewrap"><table><tr><th>Scenario</th><th>Observed result</th></tr><tr><td>Permitted USD 100 transfer</td><td>Source becomes USD 9,900; beneficiary receives USD 100</td></tr><tr><td>USD 1,000 without approval</td><td>Pending approval; no balance changes</td></tr><tr><td>Approval digest mismatch or changed policy</td><td>Rejected; no balance changes</td></tr><tr><td>Other tenant, unapproved beneficiary, or prohibited tool</td><td>Rejected before bank mutation</td></tr><tr><td>20 requests × USD 500 under USD 5,000 cap</td><td>10 completed, 10 budget-denied</td></tr><tr><td>Bank commits but response is lost</td><td>Outcome marked unknown; receipt lookup reconciles one transfer</td></tr><tr><td>Failure after debit before credit</td><td>Bank transaction rolls back; balances unchanged</td></tr><tr><td>Caller changes its arguments after snapshot</td><td>Original validated USD 100 executes</td></tr>
    <tr><td>Limit-raising and admin operations</td><td>Refused at every layer; no task grant or approval enables them</td></tr>
    <tr><td>New payee, then payment to it</td><td>Denied as a sequence although each step is permitted</td></tr>
    <tr><td>Contact change or data export, then payment</td><td>Denied as a sequence</td></tr>
    <tr><td>Freeze lifted or account opened, then payment</td><td>Escalated to a human</td></tr>
    <tr><td>Payment split into sub-threshold slices</td><td>Stopped by the cumulative task budget</td></tr>
    <tr><td>Transfer scheduled past the task's expiry</td><td>Refused; authority may not outlive the task</td></tr>
    <tr><td>Capability not granted by the task</td><td>Denied with the specific missing-capability code</td></tr></table></div></section>
    <section><h2>Which component provided each control?</h2><div class="tablewrap"><table><tr><th>Component</th><th>Attribution</th></tr><tr><td>Pramagent, existing code</td><td>Tool registration/schema checks, argument scanning, read-then-payment escalation, HMAC audit append</td></tr><tr><td>New reference controller</td><td>Task scope, strict input snapshot, exact approval, budgets, revisions, expiry, durable operation/reconciliation states</td></tr><tr><td>Mock bank</td><td>Atomic account updates, account ownership, insufficient funds, persistent idempotency receipts</td></tr><tr><td>Operator approval</td><td>Simulated application credential; real reviewer authentication is not tested</td></tr></table></div><p class="small">Original library code was not patched. This demo does not resolve earlier audit findings in other Pramagent paths.</p></section>
    <section><h2>Measured local latency</h2><div class="tablewrap"><table><tr><th>Measurement</th><th>Samples</th><th>p50</th><th>p95</th><th>p99</th></tr><tr><td>Action-summary formatting only</td><td>{latency['samples']}</td><td>{latency['p50']:.3f} µs</td><td>{latency['p95']:.3f} µs</td><td>{latency['p99']:.3f} µs</td></tr><tr><td>Complete local balance-read path</td><td>{pipeline['samples']}</td><td>{pipeline['p50']:.3f} ms</td><td>{pipeline['p95']:.3f} ms</td><td>{pipeline['p99']:.3f} ms</td></tr></table></div><p class="small">Small-sample measurements on this machine, after startup. Formatting excludes policy/IPC/storage. The complete path includes local journaling and the mock. No real bank or network latency is represented. Schema engine: {html.escape(r['schema_engine'])}.</p></section>
    <section><h2>Inspect all {r['tests_run']} scenario records</h2><p>Expand a scenario to see the decision and independent before/after bank snapshots. Every fixture checked conservation of total synthetic funds and nonnegative balances.</p>{''.join(evidence)}</section>
    <section><h2>What must be established in a real sandbox?</h2><p>Run these same outcome assertions against the actual provider's sandbox. Verify authenticated account/task binding, currency and settlement semantics, beneficiary controls, idempotency-key lifetime, status lookup after timeouts, real approvals, multiple-worker concurrency, deployment isolation, and audit recovery.</p><p><strong>Supported statement:</strong> “Pramagent v0.8.9 plus our reference controller passed {passed} documented scenarios in a local synthetic banking environment.”</p><p><strong>Not established:</strong> real-bank compatibility, bank-grade operation, compliance, distributed reliability, full dependency validation, or model-level resistance to deception.</p></section>
    <section><h2>Reproduce</h2><pre>python examples/bank_baseline/run_baseline.py\npython examples/bank_baseline/demo.py --approve-demo</pre><p class="small">The second command explicitly simulates an operator approval. The package README defines the mock contract and limitations.</p></section><footer>Report generated {datetime.now(timezone.utc).isoformat(timespec='seconds')} · All data is synthetic · Self-contained report, no external assets</footer>
    </main></body></html>'''
    # Explicit UTF-8: the report contains a U+2212 minus sign, which the
    # Windows cp1252 default codec cannot encode.
    path=ROOT/'results/report.html';path.write_text(page,encoding='utf-8');return path
if __name__=='__main__':print(build())
