"""Optional quantum-provider integrations for Pramagent."""

from .ibm_runtime import (
    IBMQuantumConfigurationError,
    IBMQuantumDependencyError,
    IBMQuantumRuntime,
    IBMRuntimeConfig,
    QuantumAuditIntegrityError,
    QuantumAttestationResult,
    QuantumBudgetExceeded,
    QuantumHardwareConsentRequired,
    QuantumLayoutQualityError,
    build_bell_circuit,
    make_ibm_hardware_policy,
    quantum_status,
)
from . import qpu_attestation
from .budget import (
    QuantumBudgetDecision,
    QuantumBudgetLedger,
    QuantumBudgetLedgerBackend,
    QuantumBudgetLimits,
    QuantumBudgetReconciliation,
    QuantumBudgetSnapshot,
)
from .budget_postgres import PostgresQuantumBudgetLedger
from .calibration import (
    CalibrationBindingError,
    CalibrationCanaryEvidence,
    CalibrationWorkloadBinding,
    record_calibration_workload_binding,
)
from .evidence import QuantumEvidenceError, QuantumExecutionEvidence
from .anchors import (
    AnchorJob,
    AnchorOutboxBackend,
    ExternalAnchorError,
    SQLiteAnchorOutbox,
    SigstoreAnchorProvider,
    attach_anchors,
)
from .anchors_postgres import AnchorLeaseLostError, PostgresAnchorOutbox
from .evidence_v2 import (
    AnchorPolicy,
    AssuranceLevel,
    CheckpointV2,
    DEFAULT_ANCHOR_POLICIES,
    DEFAULT_ANCHOR_POLICY,
    DEFAULT_SIGNATURE_POLICIES,
    DEFAULT_SIGNATURE_POLICY,
    EvidenceEnvelopeV2,
    EvidenceLeafV2,
    EvidenceV2DependencyError,
    EvidenceV2Error,
    EvidenceVerificationReport,
    ExternalAnchorV2,
    HybridCheckpointSigner,
    SignatureEntry,
    SignaturePolicy,
    SignedCheckpointV2,
    VerificationKey,
    canonicalize_jcs,
    verify_signed_checkpoint,
)
from .guarded_qnode import (
    ApprovalRequired,
    CircuitPolicy,
    GuardedQNode,
    InputPolicy,
    QuantumBudgetExceeded as PennyLaneQuantumBudgetExceeded,
    QuantumPolicyViolation,
    ResultPolicy,
    make_quantum_policies,
    pennylane_tracker_meter,
)
from .router import DifficultyScore, DifficultyScorer, HybridQuantumRouter, RouterResult
from .merkle import (
    MerkleEpochBuilder,
    consistency_proof,
    inclusion_proof,
    merkle_root,
    verify_consistency_proof,
    verify_inclusion_proof,
)
from .rfc4998 import (
    RFC4998ArchiveBundle,
    RFC4998BundleVerificationReport,
    RFC4998Error,
    RFC4998VerificationReport,
    append_timestamp_renewal,
    checkpoint_archived_object,
    create_archive_bundle,
    create_evidence_record,
    renew_archive_bundle,
    timestamp_renewal_payload,
    verify_evidence_record,
    verify_archive_bundle,
)
from .revocation import (
    REVOCATION_ARTIFACT_VERSION,
    RevocationEvidence,
    RevocationEvidenceError,
    capture_revocation_evidence,
)

__all__ = [
    "IBMQuantumConfigurationError",
    "IBMQuantumDependencyError",
    "IBMQuantumRuntime",
    "IBMRuntimeConfig",
    "QuantumAuditIntegrityError",
    "QuantumAttestationResult",
    "QuantumBudgetExceeded",
    "QuantumBudgetDecision",
    "QuantumBudgetLedger",
    "QuantumBudgetLedgerBackend",
    "QuantumBudgetLimits",
    "QuantumBudgetReconciliation",
    "QuantumBudgetSnapshot",
    "PostgresQuantumBudgetLedger",
    "PostgresAnchorOutbox",
    "CalibrationBindingError",
    "CalibrationCanaryEvidence",
    "CalibrationWorkloadBinding",
    "AnchorJob",
    "AnchorLeaseLostError",
    "AnchorOutboxBackend",
    "AnchorPolicy",
    "AssuranceLevel",
    "CheckpointV2",
    "DEFAULT_ANCHOR_POLICIES",
    "DEFAULT_ANCHOR_POLICY",
    "DEFAULT_SIGNATURE_POLICIES",
    "DEFAULT_SIGNATURE_POLICY",
    "EvidenceEnvelopeV2",
    "EvidenceLeafV2",
    "EvidenceV2DependencyError",
    "EvidenceV2Error",
    "EvidenceVerificationReport",
    "ExternalAnchorError",
    "ExternalAnchorV2",
    "HybridCheckpointSigner",
    "MerkleEpochBuilder",
    "QuantumEvidenceError",
    "QuantumExecutionEvidence",
    "QuantumHardwareConsentRequired",
    "QuantumLayoutQualityError",
    "build_bell_circuit",
    "ApprovalRequired",
    "CircuitPolicy",
    "GuardedQNode",
    "HybridQuantumRouter",
    "InputPolicy",
    "PennyLaneQuantumBudgetExceeded",
    "QuantumPolicyViolation",
    "ResultPolicy",
    "SignatureEntry",
    "SignaturePolicy",
    "SigstoreAnchorProvider",
    "SQLiteAnchorOutbox",
    "SignedCheckpointV2",
    "VerificationKey",
    "DifficultyScore",
    "DifficultyScorer",
    "RouterResult",
    "RFC4998Error",
    "RFC4998ArchiveBundle",
    "RFC4998BundleVerificationReport",
    "RFC4998VerificationReport",
    "REVOCATION_ARTIFACT_VERSION",
    "RevocationEvidence",
    "RevocationEvidenceError",
    "make_ibm_hardware_policy",
    "make_quantum_policies",
    "pennylane_tracker_meter",
    "quantum_status",
    "canonicalize_jcs",
    "attach_anchors",
    "append_timestamp_renewal",
    "checkpoint_archived_object",
    "capture_revocation_evidence",
    "consistency_proof",
    "create_evidence_record",
    "create_archive_bundle",
    "inclusion_proof",
    "merkle_root",
    "record_calibration_workload_binding",
    "renew_archive_bundle",
    "qpu_attestation",
    "verify_consistency_proof",
    "timestamp_renewal_payload",
    "verify_evidence_record",
    "verify_archive_bundle",
    "verify_inclusion_proof",
    "verify_signed_checkpoint",
]
