"""
pramagent.cli
=============
``pramagent`` CLI - project bootstrap, config validation, and quick testing.

Commands
--------
pramagent init          Generate .env and starter pramagent_config.py in the
                        current directory.
pramagent validate      Check configuration and connectivity to Redis/Postgres.
pramagent audit-verify-watch
                        Verify the audit hash chain and alert on tamper
                        detection (for cron/k8s CronJob, or --interval-s).
pramagent audit-export  Bulk-export a tenant's stored TRACE rows as JSONL
                        (Postgres-backed stores only; the trace store, NOT
                        the tamper-evident chain — see audit-verify-watch).
pramagent test-inject   Run built-in injection detection against a prompt.
pramagent redteam       Run the built-in prompt-injection benchmark.
pramagent quantum-status
                        Inspect IBM quantum dependency and credential readiness.
pramagent quantum-run   Submit a guarded Bell-pair hardware attestation.
pramagent evidence-v2-verify
                        Verify a portable evidence envelope offline.
pramagent evidence-v2-anchor
                        Timestamp and publish a V2 checkpoint externally.
pramagent hooks-doctor  Verify hook wiring, hashes, and control-plane integrity.
pramagent version       Print version.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys


def cmd_init(args) -> int:
    import os, secrets, textwrap
    cwd = os.getcwd()

    # .env
    env_path = os.path.join(cwd, ".env")
    if os.path.exists(env_path) and not args.force:
        print(f"  [skip] {env_path} already exists (use --force to overwrite)")
    else:
        api_key     = secrets.token_hex(32)
        signing_key = secrets.token_hex(32)
        jwt_secret  = secrets.token_hex(32)
        pg_pass     = secrets.token_hex(16)
        redis_pass  = secrets.token_hex(16)

        env_content = textwrap.dedent(f"""\
            # Generated by `pramagent init`
            PRAMAGENT_API_KEY={api_key}
            PRAMAGENT_SIGNING_KEY={signing_key}
            PRAMAGENT_JWT_SECRET={jwt_secret}
            POSTGRES_PASSWORD={pg_pass}
            REDIS_PASSWORD={redis_pass}
            PRAMAGENT_POSTGRES_DSN=postgresql://pramagent:{pg_pass}@localhost/pramagent
            PRAMAGENT_REDIS_URL=redis://:{redis_pass}@localhost:6379/0
            PRAMAGENT_LOG_LEVEL=info
            PRAMAGENT_MAX_INPUT_BYTES=65536
            PRAMAGENT_RATE_LIMIT_CAPACITY=100
            PRAMAGENT_RATE_LIMIT_REFILL=10
            # Optional - fill in for HITL Slack integration
            PRAMAGENT_HITL_SLACK_TOKEN=
            PRAMAGENT_HITL_SLACK_CHANNEL=
            # Optional - fill in for OpenTelemetry
            PRAMAGENT_OTEL_ENDPOINT=
            # Optional - usage analytics / billing webhook
            PRAMAGENT_BILLING_WEBHOOK_URL=
            PRAMAGENT_BILLING_WEBHOOK_SECRET=
            PRAMAGENT_BILLING_WEBHOOK_TIMEOUT_S=2.0
        """)
        # owner-only permissions: the file holds freshly generated secrets,
        # so it must never be created world-readable via the default umask
        # . No-op on Windows, where mode bits are not enforced.
        fd = os.open(env_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as f:
            f.write(env_content)
        print(f"  [ok] {env_path}")

    # starter config
    cfg_path = os.path.join(cwd, "pramagent_config.py")
    if os.path.exists(cfg_path) and not args.force:
        print(f"  [skip] {cfg_path} already exists (use --force to overwrite)")
    else:
        cfg_content = textwrap.dedent("""\
            \"\"\"
            Pramagent starter configuration.
            Edit this file to customise your trust pipeline.
            \"\"\"
            from pramagent import Pramagent
            from pramagent.config import settings
            from pramagent.layers import ToolGuardLayer, ToolPolicy
            from pramagent.layers.tool_guard import SideEffect
            from pramagent.types import Verdict

            def build_armor() -> Pramagent:
                guard = ToolGuardLayer(
                    policies=[
                        # Add your tools here
                        # ToolPolicy(
                        #     name="my_tool",
                        #     side_effect=SideEffect.READ,
                        #     schema={"type": "object", "properties": {...}},
                        # ),
                    ],
                    default_verdict=Verdict.BLOCK,
                )

                backend = settings.redis_backend()   # None if Redis not configured
                store   = settings.postgres_store()  # None if Postgres not configured

                return Pramagent(
                    tool_guard=guard,
                    store=store or None,
                    audit=store or None,
                )

            armor = build_armor()
        """)
        with open(cfg_path, "w") as f:
            f.write(cfg_content)
        print(f"  [ok] {cfg_path}")

    print("\nNext steps:")
    print("  1. Edit .env (secrets are pre-generated)")
    print("  2. Edit pramagent_config.py to register your tools")
    print("  3. From the Pramagent repo root, run: docker compose up -d")
    print("  4. pramagent validate")
    return 0


def cmd_validate(args) -> int:
    from .config import Settings
    cfg = Settings()
    warnings = cfg.validate()

    print(f"Configuration: {cfg}")
    if warnings:
        for w in warnings:
            print(f"  [warn] {w}")
    else:
        print("  [ok] all configuration checks passed")

    # Redis connectivity
    if cfg.redis_url:
        try:
            from .backends.redis_backend import RedisBackend
            b = RedisBackend.from_url(cfg.redis_url)
            ok = b.ping()
            print(f"  {'[ok]' if ok else '[fail]'} Redis: {'reachable' if ok else 'unreachable'}")
        except Exception as exc:
            print(f"  [fail] Redis: {exc}")
    else:
        print("  [-] Redis: not configured (PRAMAGENT_REDIS_URL not set)")

    # Postgres connectivity
    if cfg.postgres_dsn:
        try:
            from .store_postgres import PostgresStore, PostgresUnavailable
            PostgresStore.from_dsn(cfg.postgres_dsn, max_pool_size=1)
            print("  [ok] Postgres: reachable, DDL applied")
        except Exception as exc:
            print(f"  [fail] Postgres: {exc}")
    else:
        print("  [-] Postgres: not configured (PRAMAGENT_POSTGRES_DSN not set)")

    return 1 if warnings else 0


def _api_key_registry_from_env():
    import os
    from .auth import PostgresAPIKeyRegistry

    dsn = os.environ.get("PRAMAGENT_API_KEY_DSN", "").strip()
    if not dsn:
        raise RuntimeError(
            "PRAMAGENT_API_KEY_DSN is required for persistent key operations"
        )
    return PostgresAPIKeyRegistry.from_dsn(dsn)


def cmd_auth_issue(args) -> int:
    from .auth import encode_scopes

    try:
        registry = _api_key_registry_from_env()
        key = registry.issue_key(
            args.tenant_id,
            scopes=args.scopes,
            actor=args.actor or "",
        )
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    payload = {
        "tenant_id": args.tenant_id,
        "scopes": encode_scopes(args.scopes).split(","),
        "api_key": key,
    }
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print("[ok] API key issued; store this value now, it is shown once")
        print(f"tenant: {payload['tenant_id']}")
        print(f"scopes: {','.join(payload['scopes'])}")
        print(f"api_key: {payload['api_key']}")
    return 0


def cmd_auth_revoke(args) -> int:
    import os

    try:
        if os.environ.get("PRAMAGENT_API_KEY_DSN", "").strip():
            registry = _api_key_registry_from_env()
            revoked = registry.revoke_key(args.api_key, actor=args.actor or "")
        else:
            revocation_file = os.environ.get(
                "PRAMAGENT_API_KEY_REVOCATION_FILE", "").strip()
            if not revocation_file:
                raise RuntimeError(
                    "no revocation backend configured: set "
                    "PRAMAGENT_API_KEY_DSN for persistent-store mode, or "
                    "PRAMAGENT_API_KEY_REVOCATION_FILE to revoke keys "
                    "configured via PRAMAGENT_API_KEYS. Without either, "
                    "revoke by removing the key from PRAMAGENT_API_KEYS and "
                    "redeploying/restarting every API process (see "
                    "INCIDENT_RESPONSE_RUNBOOK.md)."
                )
            from .auth import revoke_env_key
            revoked = revoke_env_key(args.api_key, revocation_file)
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps({"revoked": bool(revoked)}, indent=2, sort_keys=True))
    else:
        print("[ok] API key revoked" if revoked else "[warn] key was not active")
    return 0 if revoked else 1


def _store_from_env():
    import os

    from .secrets import resolve_secret, resolve_signing_key_ring
    dsn = os.environ.get("PRAMAGENT_POSTGRES_DSN", "").strip()
    db_path = os.environ.get("PRAMAGENT_DB", "").strip()
    # Resolve signing and encryption keys through the same indirection layer
    # as the API, including the PRAMAGENT_SIGNING_KEYS rotation ring. A
    # single-key path here would report a
    # correctly-rotated chain (rows tagged with a newer kid) as tampered, so
    # `audit verify`/`audit-verify-watch`/`audit-export` fired false alarms.
    key_cfg = resolve_signing_key_ring()
    if dsn:
        from .store_postgres import PostgresStore
        return PostgresStore.from_dsn(dsn, **key_cfg)
    if db_path:
        key = resolve_secret("PRAMAGENT_ENCRYPTION_KEY").strip()
        if key:
            from .store_encrypted import EncryptedSQLiteStore
            return EncryptedSQLiteStore(db_path, key=key, **key_cfg)
        from .store import SQLiteStore
        return SQLiteStore(db_path, **key_cfg)
    raise RuntimeError("set PRAMAGENT_POSTGRES_DSN or PRAMAGENT_DB")


def cmd_retention_prune(args) -> int:
    import time

    if args.days < 180:
        print("[fail] retention window must be at least 180 days", file=sys.stderr)
        return 2
    if not args.tenant_id:
        print("[fail] --tenant-id is required; unscoped pruning is refused", file=sys.stderr)
        return 2

    def _run_once() -> int:
        store = _store_from_env()
        cutoff = time.time() - args.days * 86400
        pruned = store.prune_older_than(cutoff, tenant_id=args.tenant_id)
        payload = {"tenant_id": args.tenant_id, "days": args.days, "pruned": pruned}
        if args.json:
            print(json.dumps(payload, indent=2, sort_keys=True))
        else:
            print(f"[ok] pruned {pruned} trace(s) for {args.tenant_id}")
        return pruned

    if args.interval_s <= 0:
        try:
            _run_once()
        except Exception as exc:
            print(f"[fail] {exc}", file=sys.stderr)
            return 2
        return 0

    # Closes "retention pruning is invoked manually or via an external
    # cron/scheduler, not run on a loop by the app itself" — same
    # self-loop pattern as audit-verify-watch, for anyone who'd rather point
    # a long-running container at this than set up an external cron/CronJob.
    print(f"[ok] pruning every {args.interval_s}s for tenant={args.tenant_id} (Ctrl+C to stop)")
    while True:
        try:
            _run_once()
        except Exception as exc:
            print(f"[fail] prune run failed, will retry next interval: {exc}", file=sys.stderr)
        time.sleep(args.interval_s)


def cmd_audit_export(args) -> int:
    """Export stored trace rows as JSONL.

    See docs/INCIDENT_RESPONSE_RUNBOOK.md to correlate an exported
    trace with who approved a HITL action and which API key made the call
    — TraceEvent has no actor/approver field of its own, so that's a
    three-way join against the HITL queue's decided_by and
    pramagent_api_key_audit, not a single-table lookup.
    """
    if not args.tenant_id:
        print("[fail] --tenant-id is required; unscoped export is refused", file=sys.stderr)
        return 2
    try:
        store = _store_from_env()
        if not hasattr(store, "export_audit_jsonl"):
            raise RuntimeError(
                "audit-export requires a Postgres-backed store "
                "(set PRAMAGENT_POSTGRES_DSN) — SQLite/EncryptedSQLite "
                "stores don't implement bulk export yet"
            )
        exported = store.export_audit_jsonl(
            args.tenant_id, args.out, limit=args.limit)
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps(
            {"tenant_id": args.tenant_id, "out": args.out, "exported": exported},
            indent=2, sort_keys=True))
    else:
        print(f"[ok] exported {exported} record(s) for {args.tenant_id} to {args.out}")
    return 0


def _send_audit_alert(broken: list, *, source: str) -> None:
    """Best-effort POST to PRAMAGENT_AUDIT_ALERT_WEBHOOK_URL on tamper detection.

    Unlike the billing webhook, a failed alert delivery is reported loudly
    (this is a security signal, not a fail-open analytics event) — but it
    never masks the underlying chain-verification failure, which is what
    determines this command's exit code regardless of whether the alert
    itself was delivered.
    """
    import json as _json
    import os
    import urllib.error
    import urllib.request

    url = os.environ.get("PRAMAGENT_AUDIT_ALERT_WEBHOOK_URL", "").strip()
    if not url:
        return
    from .security import UnsafeURLError, validate_http_url

    try:
        safe_url = validate_http_url(
            url, allow_http_localhost=True, context="audit alert webhook URL"
        )
    except UnsafeURLError as exc:
        print(f"[warn] audit alert webhook not sent: {exc}", file=sys.stderr)
        return

    secret = os.environ.get("PRAMAGENT_AUDIT_ALERT_WEBHOOK_SECRET", "")
    timeout_s = float(os.environ.get("PRAMAGENT_AUDIT_ALERT_TIMEOUT_S", "5.0"))
    body = {
        "event": "pramagent.audit_chain_tamper_detected",
        "source": source,
        "broken_link_count": len(broken),
        "broken_links": broken[:20],  # cap payload size for large breaks
    }
    data = _json.dumps(body, sort_keys=True).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if secret:
        headers["X-Pramagent-Alert-Secret"] = secret
    req = urllib.request.Request(safe_url, data=data, headers=headers, method="POST")
    try:
        # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
        with urllib.request.urlopen(req, timeout=timeout_s) as resp:  # nosec B310
            if resp.status >= 400:
                print(f"[warn] audit alert webhook returned HTTP {resp.status}", file=sys.stderr)
    except (urllib.error.URLError, TimeoutError) as exc:
        print(f"[warn] audit alert webhook delivery failed: {exc}", file=sys.stderr)


def cmd_audit_verify_watch(args) -> int:
    """Run ``store.verify()`` once or continuously and alert on failures.

    Use ``--interval-s`` or an external scheduler for automated monitoring.
    """
    import time

    def _run_once() -> bool:
        try:
            store = _store_from_env()
        except Exception as exc:
            print(f"[fail] could not connect to store: {exc}", file=sys.stderr)
            return False
        broken = store.verify()
        if broken:
            print(f"[CRITICAL] audit chain tamper detected: {len(broken)} broken link(s)", file=sys.stderr)
            for b in broken[:20]:
                print(f"    {b}", file=sys.stderr)
            _send_audit_alert(broken, source="cli:audit-verify-watch")
            return False
        if args.json:
            print(json.dumps({"chain_valid": True, "broken_links": 0}, sort_keys=True))
        else:
            print("[ok] audit chain verified clean")
        return True

    if args.interval_s <= 0:
        return 0 if _run_once() else 1

    print(f"[ok] watching audit chain every {args.interval_s}s (Ctrl+C to stop)")
    while True:
        _run_once()
        time.sleep(args.interval_s)


def cmd_test_inject(args) -> int:
    prompt = args.prompt or input("Enter prompt to test: ")
    from .layers import IsolationLayer
    from .classifier import build_classifier
    from .layers.isolation import InjectionSuspected

    iso = IsolationLayer(
        classifier=build_classifier(force_keyword_only=not args.embedding),
        block_on_injection=False,
    )

    result = asyncio.run(iso.evaluate_input(prompt, tenant_id="cli", session_id="test"))

    hits = result.get("injection_hits", [])
    clf_flagged = result.get("classifier_flagged", False)

    if hits or clf_flagged:
        print("[warn] INJECTION SUSPECTED")
        for h in hits:
            print(f"   pattern: {h['pattern_id']} - {h['detail']}")
        if clf_flagged:
            print("   classifier: flagged")
    else:
        print("[ok] No injection detected")

    return 0


def cmd_redteam(args) -> int:
    from .redteam import EXTENDED_ATTACKS, generate_dynamic_attacks, run_injection_benchmark

    attacks = None
    mode = "static"
    seed = None
    if args.dynamic:
        attack_count = args.attacks or 100
        if attack_count < 1:
            print("--attacks must be >= 1", file=sys.stderr)
            return 2
        if attack_count > 10000:
            print("--dynamic supports up to 10000 prompts per run", file=sys.stderr)
            return 2
        generated = generate_dynamic_attacks(attack_count, seed=args.seed)
        attacks = generated.prompts
        mode = "dynamic"
        seed = generated.seed
    elif args.attacks is not None:
        if args.attacks < 1:
            print("--attacks must be >= 1", file=sys.stderr)
            return 2
        if args.attacks > len(EXTENDED_ATTACKS):
            print(
                f"--attacks supports up to {len(EXTENDED_ATTACKS)} built-in prompts",
                file=sys.stderr,
            )
            return 2
        attacks = EXTENDED_ATTACKS[:args.attacks]

    report = run_injection_benchmark(
        force_keyword_only=not args.embedding,
        attacks=attacks,
        mode=mode,
        seed=seed,
    )
    data = report.to_dict()

    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
    else:
        print("Pramagent prompt-injection benchmark")
        print(f"  attacks:          {report.attacks_caught}/{report.attacks_total} caught")
        print(f"  bypass rate:      {report.bypass_rate:.1%}")
        print(f"  mode:             {report.mode}")
        if report.seed is not None:
            print(f"  seed:             {report.seed}")
        print(f"  benign prompts:   {report.benign_total}")
        print(
            "  false positives:  "
            f"{report.false_positives} ({report.false_positive_rate:.1%})"
        )
        if report.bypassed_prompts:
            print("  bypassed prompts:")
            for prompt in report.bypassed_prompts:
                print(f"    - {prompt}")

    return 1 if report.bypass_rate > args.max_bypass_rate else 0


def cmd_version(args) -> int:
    try:
        from . import __version__
        v = __version__
    except Exception:
        try:
            from importlib.metadata import version
            v = version("pramagent")
        except Exception:
            v = "dev"
    print(f"pramagent {v}")
    return 0


def cmd_quantum_status(args) -> int:
    from .quantum import quantum_status

    try:
        status = quantum_status(connect=args.connect)
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps(status, indent=2, sort_keys=True))
        return 0
    print("Pramagent quantum status")
    print(f"  qiskit:              {status['qiskit_version'] or 'not installed'}")
    print(
        "  qiskit-ibm-runtime:  "
        f"{status['qiskit_ibm_runtime_version'] or 'not installed'}"
    )
    print(
        "  IBM credentials:     "
        f"{'configured' if status['credentials_configured'] else 'not visible'}"
    )
    print(f"  credential mode:     {status['credential_mode']}")
    if status["credentials_configured"]:
        print(f"  token source:        {status['token_source']}")
        print(f"  instance source:     {status['instance_source']}")
        if status["saved_account_names"]:
            print(f"  saved accounts:      {', '.join(status['saved_account_names'])}")
    if status["connected"] is not None:
        print(f"  provider connected:  {status['connected']}")
        print(f"  physical backends:   {status['backend_count']}")
        plans = ", ".join(status["instance_plans"]) or "not reported"
        print(f"  instance plans:      {plans}")
    return 0


def _parse_qubit_pair(value: str) -> tuple[int, int]:
    try:
        pair = tuple(int(item.strip()) for item in value.split(","))
    except ValueError as exc:
        raise argparse.ArgumentTypeError("layout must be Q0,Q1") from exc
    if len(pair) != 2 or pair[0] < 0 or pair[1] < 0 or pair[0] == pair[1]:
        raise argparse.ArgumentTypeError("layout must contain two distinct qubit IDs")
    return pair


def cmd_quantum_run(args) -> int:
    from pathlib import Path

    from .core import Pramagent
    from .quantum import (
        IBMQuantumRuntime,
        PostgresQuantumBudgetLedger,
        QuantumBudgetLedger,
        make_ibm_hardware_policy,
    )
    from .secrets import resolve_quantum_signing_key_ring
    from .store import SQLiteStore

    audit_path = Path(args.audit_db).expanduser().resolve()
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    audit_store = SQLiteStore(
        str(audit_path), **resolve_quantum_signing_key_ring()
    )
    budget_dsn = getattr(args, "budget_postgres_dsn", "").strip()
    budget_ledger = None
    try:
        budget_ledger = (
            PostgresQuantumBudgetLedger(
                budget_dsn,
                table=getattr(
                    args,
                    "budget_postgres_table",
                    "pramagent_quantum_budget_reservations",
                ),
            )
            if budget_dsn
            else QuantumBudgetLedger(audit_path)
        )
        armor = Pramagent(audit=audit_store)
        armor.tool_guard.register(
            make_ibm_hardware_policy(max_shots_per_call=args.max_shots_per_call)
        )
        runner = IBMQuantumRuntime(
            armor,
            tenant_id=args.tenant_id,
            session_id=args.session_id,
            max_shots_per_call=args.max_shots_per_call,
            max_shots_per_session=args.max_shots_per_session,
            budget_ledger=budget_ledger,
        )
        result = runner.run_hardware_attestation(
            shots=args.shots,
            backend_name=args.backend,
            confirm_hardware=args.submit_hardware,
            allow_unpriced_hardware=args.allow_unpriced_hardware,
            minimum_correlation=args.minimum_correlation,
            optimization_level=args.optimization_level,
            initial_layout=getattr(args, "initial_layout", None),
            max_layout_error_proxy=getattr(
                args, "max_layout_error_proxy", 0.05
            ),
            calibration_valid_for_seconds=getattr(
                args, "calibration_valid_for_seconds", 900.0
            ),
        )
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    finally:
        if budget_ledger is not None:
            budget_ledger.close()
        audit_store.close()
    payload = result.to_dict()
    payload["audit_db"] = str(audit_path)
    payload["budget_backend"] = "postgres" if budget_dsn else "sqlite"
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print("IBM Quantum hardware attestation")
        print(f"  backend:             {result.backend}")
        print(f"  job id:              {result.job_id}")
        print(f"  shots:               {result.shots_observed}/{result.shots_requested}")
        print(f"  counts:              {json.dumps(result.counts, sort_keys=True)}")
        print(f"  Bell correlation:    {result.bell_correlation:.3f}")
        if result.layout_error_profile:
            print(
                "  layout error proxy:  "
                f"{result.layout_error_profile['total_error_proxy']:.6f}"
            )
        print(f"  attestation passed:  {result.passed}")
        print(f"  audit chain valid:   {result.audit_chain_valid}")
        print(f"  audit database:      {audit_path}")
        print("  cost estimate:       unavailable (IBM meters QPU time, not shots)")
    return 0 if result.passed else 1


def cmd_evidence_v2_verify(args) -> int:
    from pathlib import Path

    from .quantum import (
        AssuranceLevel,
        EvidenceEnvelopeV2,
        VerificationKey,
    )

    def reject_duplicates(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"duplicate JSON property {key!r}")
            result[key] = value
        return result

    try:
        envelope = EvidenceEnvelopeV2.from_json(
            Path(args.envelope).read_bytes()
        )
        key_payload = json.loads(
            Path(args.keys).read_text(encoding="utf-8"),
            object_pairs_hook=reject_duplicates,
        )
        if isinstance(key_payload, list):
            key_items = key_payload
        elif isinstance(key_payload, dict):
            key_items = key_payload.get("keys", key_payload.get("verification_keys"))
        else:
            key_items = None
        if not isinstance(key_items, list) or not key_items:
            raise ValueError(
                "key registry must be a non-empty list or an object containing "
                "a non-empty 'keys' list"
            )
        trusted_keys = {}
        for item in key_items:
            key = VerificationKey.from_dict(item)
            identity = (key.algorithm, key.key_id)
            if identity in trusted_keys:
                raise ValueError(f"duplicate verification key {identity}")
            trusted_keys[identity] = key.public_key
        anchor_verifiers = None
        anchor_trust = getattr(args, "anchor_trust", "none")
        if anchor_trust != "none":
            from .quantum import SigstoreAnchorProvider

            provider = SigstoreAnchorProvider.production(
                offline=anchor_trust == "sigstore-offline"
            )
            anchor_verifiers = provider.verifiers()
        report = envelope.verify(
            trusted_keys=trusted_keys,
            anchor_verifiers=anchor_verifiers,
            required_assurance=AssuranceLevel(args.require_assurance),
        )
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2

    payload = report.to_dict()
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print("Pramagent Evidence Envelope V2 verification")
        print(f"  valid:                 {report.valid}")
        print(f"  assurance:             {report.assurance_level}")
        print(f"  record assurance:      {report.record_assurance}")
        print(f"  checkpoint assurance:  {report.checkpoint_assurance}")
        algorithms = ", ".join(report.checkpoint.verified_algorithms) or "none"
        print(f"  signatures verified:   {algorithms}")
        print(f"  inclusion proof:       {report.inclusion_valid}")
        print(f"  TSA verified:          {report.tsa_valid}")
        print(f"  publication verified:  {report.publication_valid}")
        for warning in report.warnings:
            print(f"  [warn] {warning}")
        for error in report.errors:
            print(f"  [fail] {error}")
    return 0 if report.valid else 1


def cmd_evidence_v2_anchor(args) -> int:
    """Queue and process external anchors for one V2 envelope."""
    from pathlib import Path

    from .quantum import (
        EvidenceEnvelopeV2,
        PostgresAnchorOutbox,
        SQLiteAnchorOutbox,
        SigstoreAnchorProvider,
        attach_anchors,
        canonicalize_jcs,
    )

    try:
        envelope = EvidenceEnvelopeV2.from_json(Path(args.envelope).read_bytes())
        provider = SigstoreAnchorProvider.production(
            offline=args.trust_cache_only,
            timeout_seconds=args.timeout,
        )
        outbox_dsn = getattr(args, "outbox_postgres_dsn", "") or os.environ.get(
            "PRAMAGENT_ANCHOR_POSTGRES_DSN", ""
        )
        if outbox_dsn:
            outbox_context = PostgresAnchorOutbox(
                outbox_dsn,
                table=getattr(
                    args, "outbox_table", "pramagent_evidence_anchor_jobs"
                ),
            )
            outbox_description = "postgres"
        else:
            outbox_context = SQLiteAnchorOutbox(args.outbox)
            outbox_description = str(Path(args.outbox).expanduser().resolve())
        with outbox_context as outbox:
            outbox.enqueue(envelope.checkpoint)
            target = outbox.get(envelope.checkpoint.checkpoint_hash)
            for _ in range(args.max_jobs):
                if target is not None and target.status == "complete":
                    break
                processed = outbox.process_one(provider)
                if processed is None:
                    break
                target = outbox.get(envelope.checkpoint.checkpoint_hash)
            if target is None:
                raise RuntimeError("anchor job was not persisted")
            if target.status != "complete":
                detail = target.last_error or "anchor job remains queued"
                raise RuntimeError(f"external anchoring incomplete: {detail}")
            anchored = attach_anchors(envelope, target.anchors)
        output = Path(args.output).expanduser().resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(canonicalize_jcs(anchored.to_dict()) + b"\n")
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2

    payload = {
        "checkpoint_hash": envelope.checkpoint.checkpoint_hash,
        "output": str(output),
        "outbox": outbox_description,
        "anchors": [anchor.to_dict() for anchor in target.anchors],
    }
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print("Pramagent Evidence Envelope V2 anchored")
        print(f"  checkpoint:          {payload['checkpoint_hash']}")
        print("  RFC 3161 timestamp:  verified")
        print("  Rekor publication:   verified")
        print(f"  output:              {output}")
        print(f"  retry outbox:        {payload['outbox']}")
    return 0


def cmd_backtest(args) -> int:
    from .policies import PolicyLoadError, backtest_policy_file

    try:
        result = backtest_policy_file(args.policy_file, args.cases)
    except PolicyLoadError as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    data = result.to_dict()
    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
    else:
        print("Pramagent policy backtest")
        print(f"  cases:      {result.total}")
        print(f"  allow:      {result.allowed}")
        print(f"  block:      {result.blocked}")
        print(f"  escalate:   {result.escalated}")
        print(f"  mismatches: {len(result.mismatches)}")
        for mismatch in result.mismatches:
            print(
                "    - "
                f"{mismatch['case_id']}: expected {mismatch['expected']}, "
                f"got {mismatch['actual']} ({mismatch['reason']})"
            )
    return 1 if result.mismatches else 0


def cmd_demo(args) -> int:
    """Run the zero-config public demo locally."""
    import os

    os.environ.setdefault("PRAMAGENT_DEMO_ENABLED", "true")
    os.environ.setdefault("PRAMAGENT_ALLOW_MEMORY_STORE", "1")
    os.environ.setdefault("PRAMAGENT_ALLOW_UNAUTHENTICATED_API", "1")
    os.environ.setdefault("PRAMAGENT_API_BIND_HOST", args.host)
    os.environ.setdefault("PRAMAGENT_PROVIDER", "mock")
    os.environ.setdefault("PRAMAGENT_DEMO_RATE_LIMIT", "60")
    try:
        import uvicorn
    except Exception:
        print(
            'uvicorn is required for `pramagent demo`; install with '
            '`pip install "pramagent[api]"`.',
            file=sys.stderr,
        )
        return 2
    url = f"http://{args.host}:{args.port}/demo"
    print(f"Pramagent demo: {url}")
    uvicorn.run(
        "pramagent.api.app:app",
        host=args.host,
        port=args.port,
        reload=args.reload,
    )
    return 0


def cmd_hooks_doctor(args) -> int:
    """Report whether coding-agent hooks are installed and tamper-evident."""
    from .hook_doctor import inspect_hooks

    report = inspect_hooks(repo_root=args.repo_root or None)
    if args.json:
        print(json.dumps(report.to_dict(), indent=2, sort_keys=True))
    else:
        for check in report.checks:
            label = {"ok": "ok", "warn": "warn", "fail": "fail"}[check.status]
            suffix = f" ({check.path})" if check.path else ""
            print(f"  [{label}] {check.name}: {check.detail}{suffix}")
        print(
            "Hook integrity: "
            + ("hardened" if report.hardened else "healthy with warnings"
               if report.healthy else "failed")
        )
    if not report.healthy:
        return 1
    return 1 if args.strict and not report.hardened else 0


def main():
    parser = argparse.ArgumentParser(
        prog="pramagent",
        description="Pramagent - AI agent trust middleware",
    )
    sub = parser.add_subparsers(dest="command")

    p_init = sub.add_parser("init", help="Bootstrap a new Pramagent project")
    p_init.add_argument("--force", action="store_true",
                        help="Overwrite existing files")

    sub.add_parser("validate", help="Validate config and connectivity")

    p_auth_issue = sub.add_parser(
        "auth-issue",
        help="Issue a persistent tenant API key in the Postgres key registry",
    )
    p_auth_issue.add_argument("tenant_id", help="Tenant that will own the key")
    p_auth_issue.add_argument(
        "--scopes",
        default="read",
        help="Comma/pipe separated scopes: read, write, admin, audit "
             "(audit alone can check chain integrity without general read "
             "access — for monitoring/alerting integrations). Defaults to "
             "read-only (A1); grant write/admin/audit explicitly.",
    )
    p_auth_issue.add_argument("--actor", default="", help="Operator id for audit trail")
    p_auth_issue.add_argument("--json", action="store_true", help="Emit JSON")

    p_auth_revoke = sub.add_parser(
        "auth-revoke",
        help="Revoke a persistent API key in the Postgres key registry",
    )
    p_auth_revoke.add_argument("api_key", help="Plain API key to revoke")
    p_auth_revoke.add_argument("--actor", default="", help="Operator id for audit trail")
    p_auth_revoke.add_argument("--json", action="store_true", help="Emit JSON")

    p_retention = sub.add_parser(
        "retention-prune",
        help="Tenant-scoped retention pruning for cron/scheduler use",
    )
    p_retention.add_argument("--tenant-id", required=True, help="Tenant to prune")
    p_retention.add_argument("--days", type=int, default=365, help="Retention window")
    p_retention.add_argument(
        "--interval-s", type=float, default=0.0,
        help="Loop forever, sleeping this many seconds between prune runs "
             "(default 0: prune once and exit)",
    )
    p_retention.add_argument("--json", action="store_true", help="Emit JSON")

    p_audit_watch = sub.add_parser(
        "audit-verify-watch",
        help="Verify the audit hash chain and alert on tamper detection "
             "(for cron/k8s CronJob, or --interval-s for a standalone loop)",
    )
    p_audit_watch.add_argument(
        "--interval-s", type=float, default=0.0,
        help="Loop forever, sleeping this many seconds between checks "
             "(default 0: check once and exit)",
    )
    p_audit_watch.add_argument("--json", action="store_true", help="Emit JSON")

    p_audit_export = sub.add_parser(
        "audit-export",
        help="Bulk-export a tenant's stored TRACE rows as JSONL "
             "(Postgres-backed stores only; this is the trace store, not the "
             "tamper-evident chain — use audit-verify-watch for integrity)",
    )
    p_audit_export.add_argument("--tenant-id", required=True, help="Tenant to export")
    p_audit_export.add_argument("--out", required=True, help="Output JSONL file path")
    p_audit_export.add_argument(
        "--limit", type=int, default=None,
        help="Max most-recent rows to export; omit to export all. Truncation "
             "(more rows exist than exported) is warned, never silent.")
    p_audit_export.add_argument("--json", action="store_true", help="Emit JSON")

    p_inj = sub.add_parser("test-inject", help="Test injection detection on a prompt")
    p_inj.add_argument("prompt", nargs="?", default="",
                       help="Prompt to test (reads from stdin if omitted)")
    p_inj.add_argument("--embedding", action="store_true",
                       help="Use embedding classifier (requires sentence-transformers)")

    p_redteam = sub.add_parser(
        "redteam",
        help="Run built-in prompt-injection benchmark",
    )
    p_redteam.add_argument(
        "--embedding",
        action="store_true",
        help="Use embedding classifier (requires sentence-transformers)",
    )
    p_redteam.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON",
    )
    p_redteam.add_argument(
        "--attacks",
        type=int,
        default=None,
        help="Number of built-in attack prompts to run",
    )
    p_redteam.add_argument(
        "--dynamic",
        "--mutate",
        action="store_true",
        dest="dynamic",
        help="Generate mutated attack prompts at runtime",
    )
    p_redteam.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Seed for reproducible dynamic prompt generation",
    )
    p_redteam.add_argument(
        "--max-bypass-rate",
        type=float,
        default=0.30,
        help="Exit non-zero if bypass rate exceeds this fraction",
    )

    p_backtest = sub.add_parser(
        "backtest",
        help="Backtest a ToolGuard policy file against JSON/JSONL cases",
    )
    p_backtest.add_argument("policy_file", help="ToolPolicy JSON/YAML file")
    p_backtest.add_argument(
        "--cases",
        required=True,
        help="JSON or JSONL tool-call cases with expected verdicts",
    )
    p_backtest.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON",
    )

    p_quantum_status = sub.add_parser(
        "quantum-status",
        help="Inspect IBM quantum dependency and credential readiness",
    )
    p_quantum_status.add_argument(
        "--connect",
        action="store_true",
        help="Authenticate and query physical backends without submitting a job",
    )
    p_quantum_status.add_argument("--json", action="store_true", help="Emit JSON")

    p_quantum_run = sub.add_parser(
        "quantum-run",
        help="Submit a guarded Bell-pair attestation to an IBM physical QPU",
    )
    p_quantum_run.add_argument("--shots", type=int, default=128)
    p_quantum_run.add_argument("--backend", default="", help="Backend name; default is least busy")
    p_quantum_run.add_argument("--tenant-id", default="local-operator")
    p_quantum_run.add_argument("--session-id", default="ibm-attestation")
    p_quantum_run.add_argument(
        "--audit-db",
        default=os.environ.get(
            "PRAMAGENT_QUANTUM_AUDIT_DB", ".pramagent/quantum-audit.db"
        ),
        help="Persistent SQLite audit-chain database",
    )
    p_quantum_run.add_argument("--max-shots-per-call", type=int, default=1024)
    p_quantum_run.add_argument("--max-shots-per-session", type=int, default=4096)
    p_quantum_run.add_argument("--minimum-correlation", type=float, default=0.60)
    p_quantum_run.add_argument("--optimization-level", type=int, choices=range(4), default=3)
    p_quantum_run.add_argument(
        "--initial-layout",
        type=_parse_qubit_pair,
        default=None,
        metavar="Q0,Q1",
        help="Force a physical qubit pair; default uses error-aware auto layout",
    )
    p_quantum_run.add_argument(
        "--max-layout-error-proxy",
        type=float,
        default=0.05,
        help="Reject the selected ISA layout above this calibration-error proxy",
    )
    p_quantum_run.add_argument(
        "--calibration-valid-for-seconds",
        type=float,
        default=900.0,
        help="Maximum age advertised by the sealed calibration canary",
    )
    p_quantum_run.add_argument(
        "--budget-postgres-dsn",
        default=os.environ.get("PRAMAGENT_QUANTUM_BUDGET_POSTGRES_DSN", ""),
        help="Use a shared Postgres quantum budget ledger (env supported)",
    )
    p_quantum_run.add_argument(
        "--budget-postgres-table",
        default="pramagent_quantum_budget_reservations",
        help="Validated table name for the shared quantum budget ledger",
    )
    p_quantum_run.add_argument(
        "--submit-hardware",
        action="store_true",
        help="Explicitly authorize submission to a physical QPU",
    )
    p_quantum_run.add_argument(
        "--allow-unpriced-hardware",
        action="store_true",
        help="Acknowledge that IBM QPU-time cost cannot be estimated per shot",
    )
    p_quantum_run.add_argument("--json", action="store_true", help="Emit JSON")

    p_evidence_verify = sub.add_parser(
        "evidence-v2-verify",
        help="Verify a V2 evidence envelope with a trusted public-key registry",
    )
    p_evidence_verify.add_argument("--envelope", required=True, help="Envelope JSON path")
    p_evidence_verify.add_argument("--keys", required=True, help="Trusted key registry JSON path")
    p_evidence_verify.add_argument(
        "--require-assurance",
        choices=(
            "checksum_only",
            "hmac_authenticated",
            "asymmetric_checkpointed",
            "tsa_anchored",
        ),
        default="asymmetric_checkpointed",
        help="Minimum accepted assurance level",
    )
    p_evidence_verify.add_argument(
        "--anchor-trust",
        choices=("none", "sigstore-offline", "sigstore-production"),
        default="none",
        help=(
            "Verify external anchors with cached or TUF-refreshed Sigstore "
            "production trust material"
        ),
    )
    p_evidence_verify.add_argument("--json", action="store_true", help="Emit JSON")

    p_evidence_anchor = sub.add_parser(
        "evidence-v2-anchor",
        help="Timestamp and publish a V2 checkpoint through Sigstore services",
    )
    p_evidence_anchor.add_argument("--envelope", required=True, help="Envelope JSON path")
    p_evidence_anchor.add_argument("--output", required=True, help="Anchored envelope output path")
    p_evidence_anchor.add_argument(
        "--outbox",
        default=".pramagent/evidence_anchor_outbox.sqlite3",
        help="Durable SQLite retry queue used when Postgres is not configured",
    )
    p_evidence_anchor.add_argument(
        "--outbox-postgres-dsn",
        default="",
        help=(
            "Distributed Postgres retry queue DSN; may also be set with "
            "PRAMAGENT_ANCHOR_POSTGRES_DSN"
        ),
    )
    p_evidence_anchor.add_argument(
        "--outbox-table",
        default="pramagent_evidence_anchor_jobs",
        help="Postgres anchor outbox table name",
    )
    p_evidence_anchor.add_argument(
        "--trust-cache-only",
        action="store_true",
        help="Use cached Sigstore TUF trust metadata without refreshing it",
    )
    p_evidence_anchor.add_argument(
        "--timeout",
        type=int,
        default=15,
        help="Per-service network timeout in seconds",
    )
    p_evidence_anchor.add_argument(
        "--max-jobs",
        type=int,
        default=100,
        help="Maximum queued jobs to process while waiting for this checkpoint",
    )
    p_evidence_anchor.add_argument("--json", action="store_true", help="Emit JSON")

    p_hooks_doctor = sub.add_parser(
        "hooks-doctor",
        help="Verify coding-agent hook wiring and runtime integrity",
    )
    p_hooks_doctor.add_argument(
        "--repo-root",
        default="",
        help="Repository containing scripts/ and plugins/ (default: installed source root)",
    )
    p_hooks_doctor.add_argument(
        "--strict",
        action="store_true",
        help="Return non-zero for warnings such as writable hook files",
    )
    p_hooks_doctor.add_argument("--json", action="store_true", help="Emit JSON")

    sub.add_parser("version", help="Print version")

    p_demo = sub.add_parser(
        "demo",
        help="Run the zero-config browser demo",
    )
    p_demo.add_argument("--host", default="127.0.0.1", help="Bind host")
    p_demo.add_argument("--port", type=int, default=8080, help="Bind port")
    p_demo.add_argument("--reload", action="store_true", help="Enable uvicorn reload")

    args = parser.parse_args()
    handlers = {
        "init":        cmd_init,
        "validate":    cmd_validate,
        "auth-issue":  cmd_auth_issue,
        "auth-revoke": cmd_auth_revoke,
        "retention-prune": cmd_retention_prune,
        "audit-verify-watch": cmd_audit_verify_watch,
        "audit-export": cmd_audit_export,
        "test-inject": cmd_test_inject,
        "redteam":     cmd_redteam,
        "backtest":    cmd_backtest,
        "quantum-status": cmd_quantum_status,
        "quantum-run": cmd_quantum_run,
        "evidence-v2-verify": cmd_evidence_v2_verify,
        "evidence-v2-anchor": cmd_evidence_v2_anchor,
        "hooks-doctor": cmd_hooks_doctor,
        "version":     cmd_version,
        "demo":        cmd_demo,
    }
    if args.command not in handlers:
        parser.print_help()
        return 1
    return handlers[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
