"""
pramagent.cli
=============
``pramagent`` CLI - project bootstrap, config validation, and quick testing.

Commands
--------
pramagent init          Generate .env and starter pramagent_config.py in the
                        current directory.
pramagent validate      Check configuration and connectivity to Redis/Postgres.
pramagent audit-verify-watch
                        Verify the audit hash chain and alert on tamper
                        detection (for cron/k8s CronJob, or --interval-s).
pramagent audit-export  Bulk-export a tenant's audit trail as JSONL
                        (Postgres-backed stores only).
pramagent test-inject   Run built-in injection detection against a prompt.
pramagent redteam       Run the built-in prompt-injection benchmark.
pramagent version       Print version.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys


def cmd_init(args) -> int:
    import os, secrets, textwrap
    cwd = os.getcwd()

    # .env
    env_path = os.path.join(cwd, ".env")
    if os.path.exists(env_path) and not args.force:
        print(f"  [skip] {env_path} already exists (use --force to overwrite)")
    else:
        api_key     = secrets.token_hex(32)
        signing_key = secrets.token_hex(32)
        jwt_secret  = secrets.token_hex(32)
        pg_pass     = secrets.token_hex(16)
        redis_pass  = secrets.token_hex(16)

        env_content = textwrap.dedent(f"""\
            # Generated by `pramagent init`
            PRAMAGENT_API_KEY={api_key}
            PRAMAGENT_SIGNING_KEY={signing_key}
            PRAMAGENT_JWT_SECRET={jwt_secret}
            POSTGRES_PASSWORD={pg_pass}
            REDIS_PASSWORD={redis_pass}
            PRAMAGENT_POSTGRES_DSN=postgresql://pramagent:{pg_pass}@localhost/pramagent
            PRAMAGENT_REDIS_URL=redis://:{redis_pass}@localhost:6379/0
            PRAMAGENT_LOG_LEVEL=info
            PRAMAGENT_MAX_INPUT_BYTES=65536
            PRAMAGENT_RATE_LIMIT_CAPACITY=100
            PRAMAGENT_RATE_LIMIT_REFILL=10
            # Optional - fill in for HITL Slack integration
            PRAMAGENT_HITL_SLACK_TOKEN=
            PRAMAGENT_HITL_SLACK_CHANNEL=
            # Optional - fill in for OpenTelemetry
            PRAMAGENT_OTEL_ENDPOINT=
            # Optional - usage analytics / billing webhook
            PRAMAGENT_BILLING_WEBHOOK_URL=
            PRAMAGENT_BILLING_WEBHOOK_SECRET=
            PRAMAGENT_BILLING_WEBHOOK_TIMEOUT_S=2.0
        """)
        # owner-only permissions: the file holds freshly generated secrets,
        # so it must never be created world-readable via the default umask
        # (P3-9). No-op on Windows, where mode bits are not enforced.
        fd = os.open(env_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as f:
            f.write(env_content)
        print(f"  [ok] {env_path}")

    # starter config
    cfg_path = os.path.join(cwd, "pramagent_config.py")
    if os.path.exists(cfg_path) and not args.force:
        print(f"  [skip] {cfg_path} already exists (use --force to overwrite)")
    else:
        cfg_content = textwrap.dedent("""\
            \"\"\"
            Pramagent starter configuration.
            Edit this file to customise your trust pipeline.
            \"\"\"
            from pramagent import Pramagent
            from pramagent.config import settings
            from pramagent.layers import ToolGuardLayer, ToolPolicy
            from pramagent.layers.tool_guard import SideEffect
            from pramagent.types import Verdict

            def build_armor() -> Pramagent:
                guard = ToolGuardLayer(
                    policies=[
                        # Add your tools here
                        # ToolPolicy(
                        #     name="my_tool",
                        #     side_effect=SideEffect.READ,
                        #     schema={"type": "object", "properties": {...}},
                        # ),
                    ],
                    default_verdict=Verdict.BLOCK,
                )

                backend = settings.redis_backend()   # None if Redis not configured
                store   = settings.postgres_store()  # None if Postgres not configured

                return Pramagent(
                    tool_guard=guard,
                    store=store or None,
                    audit=store or None,
                )

            armor = build_armor()
        """)
        with open(cfg_path, "w") as f:
            f.write(cfg_content)
        print(f"  [ok] {cfg_path}")

    print("\nNext steps:")
    print("  1. Edit .env (secrets are pre-generated)")
    print("  2. Edit pramagent_config.py to register your tools")
    print("  3. From the Pramagent repo root, run: docker compose up -d")
    print("  4. pramagent validate")
    return 0


def cmd_validate(args) -> int:
    from .config import Settings
    cfg = Settings()
    warnings = cfg.validate()

    print(f"Configuration: {cfg}")
    if warnings:
        for w in warnings:
            print(f"  [warn] {w}")
    else:
        print("  [ok] all configuration checks passed")

    # Redis connectivity
    if cfg.redis_url:
        try:
            from .backends.redis_backend import RedisBackend
            b = RedisBackend.from_url(cfg.redis_url)
            ok = b.ping()
            print(f"  {'[ok]' if ok else '[fail]'} Redis: {'reachable' if ok else 'unreachable'}")
        except Exception as exc:
            print(f"  [fail] Redis: {exc}")
    else:
        print("  [-] Redis: not configured (PRAMAGENT_REDIS_URL not set)")

    # Postgres connectivity
    if cfg.postgres_dsn:
        try:
            from .store_postgres import PostgresStore, PostgresUnavailable
            PostgresStore.from_dsn(cfg.postgres_dsn, max_pool_size=1)
            print("  [ok] Postgres: reachable, DDL applied")
        except Exception as exc:
            print(f"  [fail] Postgres: {exc}")
    else:
        print("  [-] Postgres: not configured (PRAMAGENT_POSTGRES_DSN not set)")

    return 1 if warnings else 0


def _api_key_registry_from_env():
    import os
    from .auth import PostgresAPIKeyRegistry

    dsn = os.environ.get("PRAMAGENT_API_KEY_DSN", "").strip()
    if not dsn:
        raise RuntimeError(
            "PRAMAGENT_API_KEY_DSN is required for persistent key operations"
        )
    return PostgresAPIKeyRegistry.from_dsn(dsn)


def cmd_auth_issue(args) -> int:
    from .auth import encode_scopes

    try:
        registry = _api_key_registry_from_env()
        key = registry.issue_key(
            args.tenant_id,
            scopes=args.scopes,
            actor=args.actor or "",
        )
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    payload = {
        "tenant_id": args.tenant_id,
        "scopes": encode_scopes(args.scopes).split(","),
        "api_key": key,
    }
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print("[ok] API key issued; store this value now, it is shown once")
        print(f"tenant: {payload['tenant_id']}")
        print(f"scopes: {','.join(payload['scopes'])}")
        print(f"api_key: {payload['api_key']}")
    return 0


def cmd_auth_revoke(args) -> int:
    import os

    try:
        if os.environ.get("PRAMAGENT_API_KEY_DSN", "").strip():
            registry = _api_key_registry_from_env()
            revoked = registry.revoke_key(args.api_key, actor=args.actor or "")
        else:
            revocation_file = os.environ.get(
                "PRAMAGENT_API_KEY_REVOCATION_FILE", "").strip()
            if not revocation_file:
                raise RuntimeError(
                    "no revocation backend configured: set "
                    "PRAMAGENT_API_KEY_DSN for persistent-store mode, or "
                    "PRAMAGENT_API_KEY_REVOCATION_FILE to revoke keys "
                    "configured via PRAMAGENT_API_KEYS. Without either, "
                    "revoke by removing the key from PRAMAGENT_API_KEYS and "
                    "redeploying/restarting every API process (see "
                    "INCIDENT_RESPONSE_RUNBOOK.md)."
                )
            from .auth import revoke_env_key
            revoked = revoke_env_key(args.api_key, revocation_file)
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps({"revoked": bool(revoked)}, indent=2, sort_keys=True))
    else:
        print("[ok] API key revoked" if revoked else "[warn] key was not active")
    return 0 if revoked else 1


def _store_from_env():
    import os
    dsn = os.environ.get("PRAMAGENT_POSTGRES_DSN", "").strip()
    db_path = os.environ.get("PRAMAGENT_DB", "").strip()
    signing_key = os.environ.get("PRAMAGENT_SIGNING_KEY", "").strip()
    if dsn:
        from .store_postgres import PostgresStore
        return PostgresStore.from_dsn(dsn, signing_key=signing_key)
    if db_path:
        key = os.environ.get("PRAMAGENT_ENCRYPTION_KEY", "").strip()
        if key:
            from .store_encrypted import EncryptedSQLiteStore
            return EncryptedSQLiteStore(db_path, key=key, signing_key=signing_key)
        from .store import SQLiteStore
        return SQLiteStore(db_path, signing_key=signing_key)
    raise RuntimeError("set PRAMAGENT_POSTGRES_DSN or PRAMAGENT_DB")


def cmd_retention_prune(args) -> int:
    import time

    if args.days < 180:
        print("[fail] retention window must be at least 180 days", file=sys.stderr)
        return 2
    if not args.tenant_id:
        print("[fail] --tenant-id is required; unscoped pruning is refused", file=sys.stderr)
        return 2

    def _run_once() -> int:
        store = _store_from_env()
        cutoff = time.time() - args.days * 86400
        pruned = store.prune_older_than(cutoff, tenant_id=args.tenant_id)
        payload = {"tenant_id": args.tenant_id, "days": args.days, "pruned": pruned}
        if args.json:
            print(json.dumps(payload, indent=2, sort_keys=True))
        else:
            print(f"[ok] pruned {pruned} trace(s) for {args.tenant_id}")
        return pruned

    if args.interval_s <= 0:
        try:
            _run_once()
        except Exception as exc:
            print(f"[fail] {exc}", file=sys.stderr)
            return 2
        return 0

    # Closes "retention pruning is invoked manually or via an external
    # cron/scheduler, not run on a loop by the app itself" — same
    # self-loop pattern as audit-verify-watch, for anyone who'd rather point
    # a long-running container at this than set up an external cron/CronJob.
    print(f"[ok] pruning every {args.interval_s}s for tenant={args.tenant_id} (Ctrl+C to stop)")
    while True:
        try:
            _run_once()
        except Exception as exc:
            print(f"[fail] prune run failed, will retry next interval: {exc}", file=sys.stderr)
        time.sleep(args.interval_s)


def cmd_audit_export(args) -> int:
    """CLI-reachable wrapper for PostgresStore.export_audit_jsonl(), which
    previously had no subcommand and wasn't referenced in any doc (ISSUE-12).

    See docs/INCIDENT_RESPONSE_RUNBOOK.md for how to correlate an exported
    trace with who approved a HITL action and which API key made the call
    — TraceEvent has no actor/approver field of its own, so that's a
    three-way join against the HITL queue's decided_by and
    pramagent_api_key_audit, not a single-table lookup.
    """
    if not args.tenant_id:
        print("[fail] --tenant-id is required; unscoped export is refused", file=sys.stderr)
        return 2
    try:
        store = _store_from_env()
        if not hasattr(store, "export_audit_jsonl"):
            raise RuntimeError(
                "audit-export requires a Postgres-backed store "
                "(set PRAMAGENT_POSTGRES_DSN) — SQLite/EncryptedSQLite "
                "stores don't implement bulk export yet"
            )
        exported = store.export_audit_jsonl(args.tenant_id, args.out)
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps(
            {"tenant_id": args.tenant_id, "out": args.out, "exported": exported},
            indent=2, sort_keys=True))
    else:
        print(f"[ok] exported {exported} record(s) for {args.tenant_id} to {args.out}")
    return 0


def _send_audit_alert(broken: list, *, source: str) -> None:
    """Best-effort POST to PRAMAGENT_AUDIT_ALERT_WEBHOOK_URL on tamper detection.

    Unlike the billing webhook, a failed alert delivery is reported loudly
    (this is a security signal, not a fail-open analytics event) — but it
    never masks the underlying chain-verification failure, which is what
    determines this command's exit code regardless of whether the alert
    itself was delivered.
    """
    import json as _json
    import os
    import urllib.error
    import urllib.request

    url = os.environ.get("PRAMAGENT_AUDIT_ALERT_WEBHOOK_URL", "").strip()
    if not url:
        return
    from .security import UnsafeURLError, validate_http_url

    try:
        safe_url = validate_http_url(
            url, allow_http_localhost=True, context="audit alert webhook URL"
        )
    except UnsafeURLError as exc:
        print(f"[warn] audit alert webhook not sent: {exc}", file=sys.stderr)
        return

    secret = os.environ.get("PRAMAGENT_AUDIT_ALERT_WEBHOOK_SECRET", "")
    timeout_s = float(os.environ.get("PRAMAGENT_AUDIT_ALERT_TIMEOUT_S", "5.0"))
    body = {
        "event": "pramagent.audit_chain_tamper_detected",
        "source": source,
        "broken_link_count": len(broken),
        "broken_links": broken[:20],  # cap payload size for large breaks
    }
    data = _json.dumps(body, sort_keys=True).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if secret:
        headers["X-Pramagent-Alert-Secret"] = secret
    req = urllib.request.Request(safe_url, data=data, headers=headers, method="POST")
    try:
        # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
        with urllib.request.urlopen(req, timeout=timeout_s) as resp:  # nosec B310
            if resp.status >= 400:
                print(f"[warn] audit alert webhook returned HTTP {resp.status}", file=sys.stderr)
    except (urllib.error.URLError, TimeoutError) as exc:
        print(f"[warn] audit alert webhook delivery failed: {exc}", file=sys.stderr)


def cmd_audit_verify_watch(args) -> int:
    """Run store.verify() once (or on a loop) and alert on tamper detection.

    Closes the "detection is entirely manual" gap: previously nothing called
    verify_chain() except a human hitting /v1/audit/verify or the CLI by
    hand. Point an external scheduler (cron, k8s CronJob) or --interval-s at
    this command to get automated detection with alerting.
    """
    import time

    def _run_once() -> bool:
        try:
            store = _store_from_env()
        except Exception as exc:
            print(f"[fail] could not connect to store: {exc}", file=sys.stderr)
            return False
        broken = store.verify()
        if broken:
            print(f"[CRITICAL] audit chain tamper detected: {len(broken)} broken link(s)", file=sys.stderr)
            for b in broken[:20]:
                print(f"    {b}", file=sys.stderr)
            _send_audit_alert(broken, source="cli:audit-verify-watch")
            return False
        if args.json:
            print(json.dumps({"chain_valid": True, "broken_links": 0}, sort_keys=True))
        else:
            print("[ok] audit chain verified clean")
        return True

    if args.interval_s <= 0:
        return 0 if _run_once() else 1

    print(f"[ok] watching audit chain every {args.interval_s}s (Ctrl+C to stop)")
    while True:
        _run_once()
        time.sleep(args.interval_s)


def cmd_test_inject(args) -> int:
    prompt = args.prompt or input("Enter prompt to test: ")
    from .layers import IsolationLayer
    from .classifier import build_classifier
    from .layers.isolation import InjectionSuspected

    iso = IsolationLayer(
        classifier=build_classifier(force_keyword_only=not args.embedding),
        block_on_injection=False,
    )

    result = asyncio.run(iso.evaluate_input(prompt, tenant_id="cli", session_id="test"))

    hits = result.get("injection_hits", [])
    clf_flagged = result.get("classifier_flagged", False)

    if hits or clf_flagged:
        print("[warn] INJECTION SUSPECTED")
        for h in hits:
            print(f"   pattern: {h['pattern_id']} - {h['detail']}")
        if clf_flagged:
            print("   classifier: flagged")
    else:
        print("[ok] No injection detected")

    return 0


def cmd_redteam(args) -> int:
    from .redteam import EXTENDED_ATTACKS, generate_dynamic_attacks, run_injection_benchmark

    attacks = None
    mode = "static"
    seed = None
    if args.dynamic:
        attack_count = args.attacks or 100
        if attack_count < 1:
            print("--attacks must be >= 1", file=sys.stderr)
            return 2
        if attack_count > 10000:
            print("--dynamic supports up to 10000 prompts per run", file=sys.stderr)
            return 2
        generated = generate_dynamic_attacks(attack_count, seed=args.seed)
        attacks = generated.prompts
        mode = "dynamic"
        seed = generated.seed
    elif args.attacks is not None:
        if args.attacks < 1:
            print("--attacks must be >= 1", file=sys.stderr)
            return 2
        if args.attacks > len(EXTENDED_ATTACKS):
            print(
                f"--attacks supports up to {len(EXTENDED_ATTACKS)} built-in prompts",
                file=sys.stderr,
            )
            return 2
        attacks = EXTENDED_ATTACKS[:args.attacks]

    report = run_injection_benchmark(
        force_keyword_only=not args.embedding,
        attacks=attacks,
        mode=mode,
        seed=seed,
    )
    data = report.to_dict()

    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
    else:
        print("Pramagent prompt-injection benchmark")
        print(f"  attacks:          {report.attacks_caught}/{report.attacks_total} caught")
        print(f"  bypass rate:      {report.bypass_rate:.1%}")
        print(f"  mode:             {report.mode}")
        if report.seed is not None:
            print(f"  seed:             {report.seed}")
        print(f"  benign prompts:   {report.benign_total}")
        print(
            "  false positives:  "
            f"{report.false_positives} ({report.false_positive_rate:.1%})"
        )
        if report.bypassed_prompts:
            print("  bypassed prompts:")
            for prompt in report.bypassed_prompts:
                print(f"    - {prompt}")

    return 1 if report.bypass_rate > args.max_bypass_rate else 0


def cmd_version(args) -> int:
    try:
        from . import __version__
        v = __version__
    except Exception:
        try:
            from importlib.metadata import version
            v = version("pramagent")
        except Exception:
            v = "dev"
    print(f"pramagent {v}")
    return 0


def cmd_backtest(args) -> int:
    from .policies import PolicyLoadError, backtest_policy_file

    try:
        result = backtest_policy_file(args.policy_file, args.cases)
    except PolicyLoadError as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 2
    data = result.to_dict()
    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
    else:
        print("Pramagent policy backtest")
        print(f"  cases:      {result.total}")
        print(f"  allow:      {result.allowed}")
        print(f"  block:      {result.blocked}")
        print(f"  escalate:   {result.escalated}")
        print(f"  mismatches: {len(result.mismatches)}")
        for mismatch in result.mismatches:
            print(
                "    - "
                f"{mismatch['case_id']}: expected {mismatch['expected']}, "
                f"got {mismatch['actual']} ({mismatch['reason']})"
            )
    return 1 if result.mismatches else 0


def cmd_demo(args) -> int:
    """Run the zero-config public demo locally."""
    import os

    os.environ.setdefault("PRAMAGENT_DEMO_ENABLED", "true")
    os.environ.setdefault("PRAMAGENT_ALLOW_MEMORY_STORE", "1")
    os.environ.setdefault("PRAMAGENT_ALLOW_UNAUTHENTICATED_API", "1")
    os.environ.setdefault("PRAMAGENT_API_BIND_HOST", args.host)
    os.environ.setdefault("PRAMAGENT_PROVIDER", "mock")
    os.environ.setdefault("PRAMAGENT_DEMO_RATE_LIMIT", "60")
    try:
        import uvicorn
    except Exception:
        print(
            'uvicorn is required for `pramagent demo`; install with '
            '`pip install "pramagent[api]"`.',
            file=sys.stderr,
        )
        return 2
    url = f"http://{args.host}:{args.port}/demo"
    print(f"Pramagent demo: {url}")
    uvicorn.run(
        "pramagent.api.app:app",
        host=args.host,
        port=args.port,
        reload=args.reload,
    )
    return 0


def main():
    parser = argparse.ArgumentParser(
        prog="pramagent",
        description="Pramagent - AI agent trust middleware",
    )
    sub = parser.add_subparsers(dest="command")

    p_init = sub.add_parser("init", help="Bootstrap a new Pramagent project")
    p_init.add_argument("--force", action="store_true",
                        help="Overwrite existing files")

    sub.add_parser("validate", help="Validate config and connectivity")

    p_auth_issue = sub.add_parser(
        "auth-issue",
        help="Issue a persistent tenant API key in the Postgres key registry",
    )
    p_auth_issue.add_argument("tenant_id", help="Tenant that will own the key")
    p_auth_issue.add_argument(
        "--scopes",
        default="read,write,admin",
        help="Comma/pipe separated scopes: read, write, admin, audit "
             "(audit alone can check chain integrity without general read "
             "access — for monitoring/alerting integrations)",
    )
    p_auth_issue.add_argument("--actor", default="", help="Operator id for audit trail")
    p_auth_issue.add_argument("--json", action="store_true", help="Emit JSON")

    p_auth_revoke = sub.add_parser(
        "auth-revoke",
        help="Revoke a persistent API key in the Postgres key registry",
    )
    p_auth_revoke.add_argument("api_key", help="Plain API key to revoke")
    p_auth_revoke.add_argument("--actor", default="", help="Operator id for audit trail")
    p_auth_revoke.add_argument("--json", action="store_true", help="Emit JSON")

    p_retention = sub.add_parser(
        "retention-prune",
        help="Tenant-scoped retention pruning for cron/scheduler use",
    )
    p_retention.add_argument("--tenant-id", required=True, help="Tenant to prune")
    p_retention.add_argument("--days", type=int, default=365, help="Retention window")
    p_retention.add_argument(
        "--interval-s", type=float, default=0.0,
        help="Loop forever, sleeping this many seconds between prune runs "
             "(default 0: prune once and exit)",
    )
    p_retention.add_argument("--json", action="store_true", help="Emit JSON")

    p_audit_watch = sub.add_parser(
        "audit-verify-watch",
        help="Verify the audit hash chain and alert on tamper detection "
             "(for cron/k8s CronJob, or --interval-s for a standalone loop)",
    )
    p_audit_watch.add_argument(
        "--interval-s", type=float, default=0.0,
        help="Loop forever, sleeping this many seconds between checks "
             "(default 0: check once and exit)",
    )
    p_audit_watch.add_argument("--json", action="store_true", help="Emit JSON")

    p_audit_export = sub.add_parser(
        "audit-export",
        help="Bulk-export a tenant's audit trail as JSONL "
             "(Postgres-backed stores only)",
    )
    p_audit_export.add_argument("--tenant-id", required=True, help="Tenant to export")
    p_audit_export.add_argument("--out", required=True, help="Output JSONL file path")
    p_audit_export.add_argument("--json", action="store_true", help="Emit JSON")

    p_inj = sub.add_parser("test-inject", help="Test injection detection on a prompt")
    p_inj.add_argument("prompt", nargs="?", default="",
                       help="Prompt to test (reads from stdin if omitted)")
    p_inj.add_argument("--embedding", action="store_true",
                       help="Use embedding classifier (requires sentence-transformers)")

    p_redteam = sub.add_parser(
        "redteam",
        help="Run built-in prompt-injection benchmark",
    )
    p_redteam.add_argument(
        "--embedding",
        action="store_true",
        help="Use embedding classifier (requires sentence-transformers)",
    )
    p_redteam.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON",
    )
    p_redteam.add_argument(
        "--attacks",
        type=int,
        default=None,
        help="Number of built-in attack prompts to run",
    )
    p_redteam.add_argument(
        "--dynamic",
        "--mutate",
        action="store_true",
        dest="dynamic",
        help="Generate mutated attack prompts at runtime",
    )
    p_redteam.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Seed for reproducible dynamic prompt generation",
    )
    p_redteam.add_argument(
        "--max-bypass-rate",
        type=float,
        default=0.30,
        help="Exit non-zero if bypass rate exceeds this fraction",
    )

    p_backtest = sub.add_parser(
        "backtest",
        help="Backtest a ToolGuard policy file against JSON/JSONL cases",
    )
    p_backtest.add_argument("policy_file", help="ToolPolicy JSON/YAML file")
    p_backtest.add_argument(
        "--cases",
        required=True,
        help="JSON or JSONL tool-call cases with expected verdicts",
    )
    p_backtest.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON",
    )

    sub.add_parser("version", help="Print version")

    p_demo = sub.add_parser(
        "demo",
        help="Run the zero-config browser demo",
    )
    p_demo.add_argument("--host", default="127.0.0.1", help="Bind host")
    p_demo.add_argument("--port", type=int, default=8080, help="Bind port")
    p_demo.add_argument("--reload", action="store_true", help="Enable uvicorn reload")

    args = parser.parse_args()
    handlers = {
        "init":        cmd_init,
        "validate":    cmd_validate,
        "auth-issue":  cmd_auth_issue,
        "auth-revoke": cmd_auth_revoke,
        "retention-prune": cmd_retention_prune,
        "audit-verify-watch": cmd_audit_verify_watch,
        "audit-export": cmd_audit_export,
        "test-inject": cmd_test_inject,
        "redteam":     cmd_redteam,
        "backtest":    cmd_backtest,
        "version":     cmd_version,
        "demo":        cmd_demo,
    }
    if args.command not in handlers:
        parser.print_help()
        return 1
    return handlers[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
