"""
pramagent.cli
=============
``pramagent`` CLI - project bootstrap, config validation, and quick testing.

Commands
--------
pramagent init          Generate .env and starter pramagent_config.py in the
                        current directory.
pramagent validate      Check configuration and connectivity to Redis/Postgres.
pramagent test-inject   Run built-in injection detection against a prompt.
pramagent redteam       Run the built-in prompt-injection benchmark.
pramagent version       Print version.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys


def cmd_init(args) -> int:
    import os, secrets, textwrap
    cwd = os.getcwd()

    # .env
    env_path = os.path.join(cwd, ".env")
    if os.path.exists(env_path) and not args.force:
        print(f"  [skip] {env_path} already exists (use --force to overwrite)")
    else:
        api_key     = secrets.token_hex(32)
        signing_key = secrets.token_hex(32)
        jwt_secret  = secrets.token_hex(32)
        pg_pass     = secrets.token_hex(16)
        redis_pass  = secrets.token_hex(16)

        env_content = textwrap.dedent(f"""\
            # Generated by `pramagent init`
            PRAMAGENT_API_KEY={api_key}
            PRAMAGENT_SIGNING_KEY={signing_key}
            PRAMAGENT_JWT_SECRET={jwt_secret}
            POSTGRES_PASSWORD={pg_pass}
            REDIS_PASSWORD={redis_pass}
            PRAMAGENT_POSTGRES_DSN=postgresql://pramagent:{pg_pass}@localhost/pramagent
            PRAMAGENT_REDIS_URL=redis://:{redis_pass}@localhost:6379/0
            PRAMAGENT_LOG_LEVEL=info
            PRAMAGENT_MAX_INPUT_BYTES=65536
            PRAMAGENT_RATE_LIMIT_CAPACITY=100
            PRAMAGENT_RATE_LIMIT_REFILL=10
            # Optional - fill in for HITL Slack integration
            PRAMAGENT_HITL_SLACK_TOKEN=
            PRAMAGENT_HITL_SLACK_CHANNEL=
            # Optional - fill in for OpenTelemetry
            PRAMAGENT_OTEL_ENDPOINT=
            # Optional - usage analytics / billing webhook
            PRAMAGENT_BILLING_WEBHOOK_URL=
            PRAMAGENT_BILLING_WEBHOOK_SECRET=
            PRAMAGENT_BILLING_WEBHOOK_TIMEOUT_S=2.0
        """)
        # owner-only permissions: the file holds freshly generated secrets,
        # so it must never be created world-readable via the default umask
        # (P3-9). No-op on Windows, where mode bits are not enforced.
        fd = os.open(env_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as f:
            f.write(env_content)
        print(f"  [ok] {env_path}")

    # starter config
    cfg_path = os.path.join(cwd, "pramagent_config.py")
    if os.path.exists(cfg_path) and not args.force:
        print(f"  [skip] {cfg_path} already exists (use --force to overwrite)")
    else:
        cfg_content = textwrap.dedent("""\
            \"\"\"
            Pramagent starter configuration.
            Edit this file to customise your trust pipeline.
            \"\"\"
            from pramagent import Pramagent
            from pramagent.config import settings
            from pramagent.layers import ToolGuardLayer, ToolPolicy
            from pramagent.layers.tool_guard import SideEffect
            from pramagent.types import Verdict

            def build_armor() -> Pramagent:
                guard = ToolGuardLayer(
                    policies=[
                        # Add your tools here
                        # ToolPolicy(
                        #     name="my_tool",
                        #     side_effect=SideEffect.READ,
                        #     schema={"type": "object", "properties": {...}},
                        # ),
                    ],
                    default_verdict=Verdict.BLOCK,
                )

                backend = settings.redis_backend()   # None if Redis not configured
                store   = settings.postgres_store()  # None if Postgres not configured

                return Pramagent(
                    tool_guard=guard,
                    store=store or None,
                    audit=store or None,
                )

            armor = build_armor()
        """)
        with open(cfg_path, "w") as f:
            f.write(cfg_content)
        print(f"  [ok] {cfg_path}")

    print("\nNext steps:")
    print("  1. Edit .env (secrets are pre-generated)")
    print("  2. Edit pramagent_config.py to register your tools")
    print("  3. From the Pramagent repo root, run: docker compose up -d")
    print("  4. pramagent validate")
    return 0


def cmd_validate(args) -> int:
    from .config import Settings
    cfg = Settings()
    warnings = cfg.validate()

    print(f"Configuration: {cfg}")
    if warnings:
        for w in warnings:
            print(f"  [warn] {w}")
    else:
        print("  [ok] all configuration checks passed")

    # Redis connectivity
    if cfg.redis_url:
        try:
            from .backends.redis_backend import RedisBackend
            b = RedisBackend.from_url(cfg.redis_url)
            ok = b.ping()
            print(f"  {'[ok]' if ok else '[fail]'} Redis: {'reachable' if ok else 'unreachable'}")
        except Exception as exc:
            print(f"  [fail] Redis: {exc}")
    else:
        print("  [-] Redis: not configured (PRAMAGENT_REDIS_URL not set)")

    # Postgres connectivity
    if cfg.postgres_dsn:
        try:
            from .store_postgres import PostgresStore, PostgresUnavailable
            PostgresStore.from_dsn(cfg.postgres_dsn, max_pool_size=1)
            print("  [ok] Postgres: reachable, DDL applied")
        except Exception as exc:
            print(f"  [fail] Postgres: {exc}")
    else:
        print("  [-] Postgres: not configured (PRAMAGENT_POSTGRES_DSN not set)")

    return 1 if warnings else 0


def cmd_test_inject(args) -> int:
    prompt = args.prompt or input("Enter prompt to test: ")
    from .layers import IsolationLayer
    from .classifier import build_classifier
    from .layers.isolation import InjectionSuspected

    iso = IsolationLayer(
        classifier=build_classifier(force_keyword_only=not args.embedding),
        block_on_injection=False,
    )

    result = asyncio.run(iso.evaluate_input(prompt, tenant_id="cli", session_id="test"))

    hits = result.get("injection_hits", [])
    clf_flagged = result.get("classifier_flagged", False)

    if hits or clf_flagged:
        print("[warn] INJECTION SUSPECTED")
        for h in hits:
            print(f"   pattern: {h['pattern_id']} - {h['detail']}")
        if clf_flagged:
            print("   classifier: flagged")
    else:
        print("[ok] No injection detected")

    return 0


def cmd_redteam(args) -> int:
    from .redteam import EXTENDED_ATTACKS, generate_dynamic_attacks, run_injection_benchmark

    attacks = None
    mode = "static"
    seed = None
    if args.dynamic:
        attack_count = args.attacks or 100
        if attack_count < 1:
            print("--attacks must be >= 1", file=sys.stderr)
            return 2
        if attack_count > 10000:
            print("--dynamic supports up to 10000 prompts per run", file=sys.stderr)
            return 2
        generated = generate_dynamic_attacks(attack_count, seed=args.seed)
        attacks = generated.prompts
        mode = "dynamic"
        seed = generated.seed
    elif args.attacks is not None:
        if args.attacks < 1:
            print("--attacks must be >= 1", file=sys.stderr)
            return 2
        if args.attacks > len(EXTENDED_ATTACKS):
            print(
                f"--attacks supports up to {len(EXTENDED_ATTACKS)} built-in prompts",
                file=sys.stderr,
            )
            return 2
        attacks = EXTENDED_ATTACKS[:args.attacks]

    report = run_injection_benchmark(
        force_keyword_only=not args.embedding,
        attacks=attacks,
        mode=mode,
        seed=seed,
    )
    data = report.to_dict()

    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
    else:
        print("Pramagent prompt-injection benchmark")
        print(f"  attacks:          {report.attacks_caught}/{report.attacks_total} caught")
        print(f"  bypass rate:      {report.bypass_rate:.1%}")
        print(f"  mode:             {report.mode}")
        if report.seed is not None:
            print(f"  seed:             {report.seed}")
        print(f"  benign prompts:   {report.benign_total}")
        print(
            "  false positives:  "
            f"{report.false_positives} ({report.false_positive_rate:.1%})"
        )
        if report.bypassed_prompts:
            print("  bypassed prompts:")
            for prompt in report.bypassed_prompts:
                print(f"    - {prompt}")

    return 1 if report.bypass_rate > args.max_bypass_rate else 0


def cmd_version(args) -> int:
    try:
        from . import __version__
        v = __version__
    except Exception:
        try:
            from importlib.metadata import version
            v = version("pramagent")
        except Exception:
            v = "dev"
    print(f"pramagent {v}")
    return 0


def cmd_demo(args) -> int:
    """Run the zero-config public demo locally."""
    import os

    os.environ.setdefault("PRAMAGENT_DEMO_ENABLED", "true")
    os.environ.setdefault("PRAMAGENT_ALLOW_MEMORY_STORE", "1")
    os.environ.setdefault("PRAMAGENT_PROVIDER", "mock")
    os.environ.setdefault("PRAMAGENT_DEMO_RATE_LIMIT", "60")
    try:
        import uvicorn
    except Exception:
        print(
            'uvicorn is required for `pramagent demo`; install with '
            '`pip install "pramagent[api]"`.',
            file=sys.stderr,
        )
        return 2
    url = f"http://{args.host}:{args.port}/demo"
    print(f"Pramagent demo: {url}")
    uvicorn.run(
        "pramagent.api.app:app",
        host=args.host,
        port=args.port,
        reload=args.reload,
    )
    return 0


def main():
    parser = argparse.ArgumentParser(
        prog="pramagent",
        description="Pramagent - AI agent trust middleware",
    )
    sub = parser.add_subparsers(dest="command")

    p_init = sub.add_parser("init", help="Bootstrap a new Pramagent project")
    p_init.add_argument("--force", action="store_true",
                        help="Overwrite existing files")

    sub.add_parser("validate", help="Validate config and connectivity")

    p_inj = sub.add_parser("test-inject", help="Test injection detection on a prompt")
    p_inj.add_argument("prompt", nargs="?", default="",
                       help="Prompt to test (reads from stdin if omitted)")
    p_inj.add_argument("--embedding", action="store_true",
                       help="Use embedding classifier (requires sentence-transformers)")

    p_redteam = sub.add_parser(
        "redteam",
        help="Run built-in prompt-injection benchmark",
    )
    p_redteam.add_argument(
        "--embedding",
        action="store_true",
        help="Use embedding classifier (requires sentence-transformers)",
    )
    p_redteam.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON",
    )
    p_redteam.add_argument(
        "--attacks",
        type=int,
        default=None,
        help="Number of built-in attack prompts to run",
    )
    p_redteam.add_argument(
        "--dynamic",
        "--mutate",
        action="store_true",
        dest="dynamic",
        help="Generate mutated attack prompts at runtime",
    )
    p_redteam.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Seed for reproducible dynamic prompt generation",
    )
    p_redteam.add_argument(
        "--max-bypass-rate",
        type=float,
        default=0.30,
        help="Exit non-zero if bypass rate exceeds this fraction",
    )

    sub.add_parser("version", help="Print version")

    p_demo = sub.add_parser(
        "demo",
        help="Run the zero-config browser demo",
    )
    p_demo.add_argument("--host", default="127.0.0.1", help="Bind host")
    p_demo.add_argument("--port", type=int, default=8080, help="Bind port")
    p_demo.add_argument("--reload", action="store_true", help="Enable uvicorn reload")

    args = parser.parse_args()
    handlers = {
        "init":        cmd_init,
        "validate":    cmd_validate,
        "test-inject": cmd_test_inject,
        "redteam":     cmd_redteam,
        "version":     cmd_version,
        "demo":        cmd_demo,
    }
    if args.command not in handlers:
        parser.print_help()
        return 1
    return handlers[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
